  name: flutter_application_1
  description: "A new Flutter project."
  publish_to: 'none'
  version: 0.1.0

  environment:
    sdk: ^3.5.3

  dependencies:
    flutter:
      sdk: flutter
    get: ^4.6.6
    flutter_launcher_icons: ^0.9.2
    just_audio: ^0.9.42
    on_audio_query: ^2.9.0
    permission_handler: ^11.3.1
    flutter_native_splash: ^2.2.4


  flutter_native_splash:
    android: true
    ios: true
    web: false
    background_image: "assets/download (5).jpeg"
    image: "assets/1113.png"
    ios_content_mode: scaleAspectFill
    

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true
    fonts:
      - family: JosefinSans
        fonts:
          - asset: assets/JosefinSans-Regular.ttf
          - asset: assets/JosefinSans-Bold.ttf
        
  flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon/app_icon.png"


   